import mongoose, { Schema, Model, Document } from 'mongoose';

export interface IAIReport extends Document {
  title: string;
  type: 'sales_prediction' | 'inventory_optimization' | 'business_insight' | 'performance_analysis';
  query: string;
  response: string;
  data: Record<string, any>;
  confidence: number;
  generatedBy: mongoose.Types.ObjectId;
  branchId?: mongoose.Types.ObjectId;
  tags: string[];
  isHelpful?: boolean;
  createdAt: Date;
  updatedAt: Date;
}

const AIReportSchema = new Schema<IAIReport>(
  {
    title: {
      type: String,
      required: [true, 'Report title is required'],
      trim: true,
    },
    type: {
      type: String,
      enum: ['sales_prediction', 'inventory_optimization', 'business_insight', 'performance_analysis'],
      required: [true, 'Report type is required'],
    },
    query: {
      type: String,
      required: [true, 'Query is required'],
      trim: true,
    },
    response: {
      type: String,
      required: [true, 'Response is required'],
    },
    data: {
      type: Schema.Types.Mixed,
      default: {},
    },
    confidence: {
      type: Number,
      min: [0, 'Confidence cannot be negative'],
      max: [100, 'Confidence cannot exceed 100'],
      default: 0,
    },
    generatedBy: {
      type: Schema.Types.ObjectId,
      ref: 'User',
      required: [true, 'Generated by is required'],
    },
    branchId: {
      type: Schema.Types.ObjectId,
      ref: 'Branch',
    },
    tags: [{
      type: String,
    }],
    isHelpful: {
      type: Boolean,
    },
  },
  {
    timestamps: true,
  }
);

AIReportSchema.index({ type: 1, createdAt: -1 });
AIReportSchema.index({ generatedBy: 1 });

const AIReport: Model<IAIReport> = mongoose.models.AIReport || mongoose.model<IAIReport>('AIReport', AIReportSchema);

export default AIReport;
